### ISSUE TITLE
Use Embeds in Ephemeral Responses

### ISSUE THREAD

**Issue by CodyJasonBennett** [threejs/discord-bot#22]
In #16, commands moved completely to interactions, dropping message support.

In the next API deployment of Discord, embeds in ephemeral messages will be supported to have continuity between the messages workflow and interactions.

With this, we can safely support the message workflow without creating another path.

**Comment by GmBodhi** [comment]
I think they've added that recently
![image](https://user-images.githubusercontent.com/71921036/117310156-a7e90a00-aea0-11eb-9466-21d61e6e50ce.png)

**Comment by CodyJasonBennett** [comment]
Yes, it seems they have.

**Comment by CodyJasonBennett** [comment]
Implemented in #23.
