### ISSUE TITLE
Update on Doc Changes/New Release

### ISSUE THREAD

**Issue by CodyJasonBennett** [threejs/discord-bot#25]
Currently, docs are generated on startup, but there's no system in place to update them.

If [three.js#21885](https://github.com/mrdoob/three.js/pull/21885) is merged, I propose generating on fetch and using page headers/GH API to determine whether an update has been made.

**Comment by vaish567** [comment]
Howdy @CodyJasonBennett. Can I step up on this issue as this would be my first pull request. 
:)

**Comment by CodyJasonBennett** [comment]
@vaish567, sure thing, and I appreciate the help.

**Comment by vaish567** [comment]
Hello @CodyJasonBennett I'm still not able to figure out the problem? Could you please elaborate?

**Comment by CodyJasonBennett** [comment]
@vaish567, three.js has monthly releases with changes to documentation and examples. The bot needs to detect a new(er) release and regenerate its collections of docs and examples.

**Comment by GmBodhi** [comment]
I think the script for generating docs is in my three.js fork I guess.
