### ISSUE TITLE
!examples partial_string does not work

### ISSUE THREAD

**Issue by makc** [threejs/discord-bot#3]
![Screen Shot 2021-03-04 at 14 43 03 ](https://user-images.githubusercontent.com/242577/109972796-fbe83e80-7cf7-11eb-9ab2-1795fa6d8833.png)

**Comment by CodyJasonBennett** [comment]
Underscores has the bot check for exact matches, but I worked in fuzzy searching in [08c01ec](https://github.com/threejs/discord-bot/commit/08c01ec9b7f4437ecfd0e2263acb65fcf91f9414).
