### ISSUE TITLE
feat(tags): add tags, which will send certain message for specific tag

### ISSUE THREAD

**Issue by GmBodhi** [threejs/discord-bot#30]
As mentioned by [Frawg](https://ptb.discord.com/channels/685241246557667386/816009690415890524/878625190219755620)

**Comment by CodyJasonBennett** [comment]
I think his specific use-case is a bit spammy or even malicious, but giving users the ability to display resources by invoking a command can do.

**Comment by GmBodhi** [comment]
I think we can make an algorithm, such that if someone uses this rapidly, we can blacklist them for some time. If (s)he does this again, the bot will temporarily ban him from using tags unless some admins unban him (her).

**Comment by GmBodhi** [comment]
As this is an impractical or time burning task, hereby closing the issue 👀
